name: Deploy to EC2

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Build Next.js app
      run: |
        npm ci
        npm run build

    - name: Deploy via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/OmniConvo

    - name: Restart service
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "sudo systemctl restart jomniconvo.service"
